- id: go-vulncheck
  name: Check for golang vulnerabilities
  description: prevents vulnerabilities from being committed.
  entry: govuln
  language: golang
  stages: [pre-commit, pre-push, manual]
  minimum_pre_commit_version: 3.2.0
  pass_filenames: false
  always_run: true
  additional_dependencies:
    - golang.org/x/vuln/cmd/govulncheck@latest
