[project]
name = "govuln-precommit"
version = "0.0.10"
description = "pre-commit hook for vulnerabilites checking in golang projects"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]
[project.scripts]
go-vulncheck = "govuln.govulncheck:main"
